name: FNews
version: 5.0
main: org.fnews.FNews
api-version: '1.16'
authors: [MCFireStudioTeam]
description: A minecraft chat plugin
website: https://github.com/MCFireStudio/fnews.git
commands:
  fnews:
    permission: fnews.use
  fnews-reload:
    permission: fnews.reload
